# 1. LabelEncoder
將類別標籤轉換為數字編碼，適用於有順序關係的類別變數。

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
data = pd.DataFrame({
    'Fruits':['Kewi','Apple','Banana','Cherry'],
})
le = LabelEncoder()
data["Fruit_numer"] = le.fit_transform(data["Fruits"])
data

Fruits  Fruit_numer
0    Kewi            3
1   Apple            0
2  Banana            1
3  Cherry            2

# 2. OneHotEncoder

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# 建立一個範例 DataFrame
data = pd.DataFrame({
    'Color':['Red','Green','Blue','Green','Red']
})

In [4]:
ohe = OneHotEncoder()
on_hot_code = ohe.fit_transform(data[["Color"]])
print(on_hot_code)

  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0
  (3, 1)	1.0
  (4, 2)	1.0


In [5]:
ohe = OneHotEncoder(sparse_output = False)
on_hot_code = ohe.fit_transform(data[["Color"]])
print(on_hot_code)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
colName = ohe.get_feature_names_out(["Color"])
print(colName)
one_hot_df = pd.DataFrame(on_hot_code, columns = colName)
print(one_hot_df)

['Color_Blue' 'Color_Green' 'Color_Red']
   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0


In [7]:
data = data.join(one_hot_df)
data

Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1  Green         0.0          1.0        0.0
2   Blue         1.0          0.0        0.0
3  Green         0.0          1.0        0.0
4    Red         0.0          0.0        1.0

In [8]:
import pandas as pd
# 建立一個範例 DataFrame
data = pd.DataFrame({
    'Color':['Red','Green','Blue','Green','Red']
})
one_hot_df = pd.get_dummies(data, columns = ["Color"])
print(one_hot_df)
one_hot_df_int = one_hot_df.astype(int)
print(one_hot_df_int)

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1       False         True      False
2        True        False      False
3       False         True      False
4       False        False       True
   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
3           0            1          0
4           0            0          1


# 3. 共線(Collinearity)

In [9]:
import pandas as pd
# 建立一個範例 DataFrame
data = pd.DataFrame({
    'Color':['Red','Green','Blue','Green','Red']
})
one_hot_df = pd.get_dummies(data, columns = ["Color"], drop_first = True)
one_hot_df = one_hot_df.astype(int)
one_hot_df

Color_Green  Color_Red
0            0          1
1            1          0
2            0          0
3            1          0
4            0          1

# 4. Ames_NO_Missing_Data.csv

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv("./Ames_NO_Missing_Data.csv")
df.head()

MS SubClass MS Zoning  Lot Frontage  Lot Area Street Lot Shape  \
0           20        RL         141.0     31770   Pave       IR1   
1           20        RH          80.0     11622   Pave       Reg   
2           20        RL          81.0     14267   Pave       IR1   
3           20        RL          93.0     11160   Pave       Reg   
4           60        RL          74.0     13830   Pave       IR1   

  Land Contour Utilities Lot Config Land Slope  ... Enclosed Porch 3Ssn Porch  \
0          Lvl    AllPub     Corner        Gtl  ...              0          0   
1          Lvl    AllPub     Inside        Gtl  ...              0          0   
2          Lvl    AllPub     Corner        Gtl  ...              0          0   
3          Lvl    AllPub     Corner        Gtl  ...              0          0   
4          Lvl    AllPub     Inside        Gtl  ...              0          0   

  Screen Porch Pool Area Misc Val  Mo Sold  Yr Sold  Sale Type  \
0            0         0        0        5     2010        WD    
1          120         0        0        6     2010        WD    
2            0         0    12500        6     2010        WD    
3            0         0        0        4     2010        WD    
4            0         0        0        3     2010        WD    

   Sale Condition SalePrice  
0          Normal    215000  
1          Normal    105000  
2          Normal    172000  
3          Normal    244000  
4          Normal    189900  

[5 rows x 76 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 76 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   MS SubClass      2925 non-null   int64  
 1   MS Zoning        2925 non-null   object 
 2   Lot Frontage     2925 non-null   float64
 3   Lot Area         2925 non-null   int64  
 4   Street           2925 non-null   object 
 5   Lot Shape        2925 non-null   object 
 6   Land Contour     2925 non-null   object 
 7   Utilities        2925 non-null   object 
 8   Lot Config       2925 non-null   object 
 9   Land Slope       2925 non-null   object 
 10  Neighborhood     2925 non-null   object 
 11  Condition 1      2925 non-null   object 
 12  Condition 2      2925 non-null   object 
 13  Bldg Type        2925 non-null   object 
 14  House Style      2925 non-null   object 
 15  Overall Qual     2925 non-null   int64  
 16  Overall Cond     2925 non-null   int64  
 17  Year Built    

In [13]:
df["MS SubClass"] = df["MS SubClass"].astype(str)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 76 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   MS SubClass      2925 non-null   object 
 1   MS Zoning        2925 non-null   object 
 2   Lot Frontage     2925 non-null   float64
 3   Lot Area         2925 non-null   int64  
 4   Street           2925 non-null   object 
 5   Lot Shape        2925 non-null   object 
 6   Land Contour     2925 non-null   object 
 7   Utilities        2925 non-null   object 
 8   Lot Config       2925 non-null   object 
 9   Land Slope       2925 non-null   object 
 10  Neighborhood     2925 non-null   object 
 11  Condition 1      2925 non-null   object 
 12  Condition 2      2925 non-null   object 
 13  Bldg Type        2925 non-null   object 
 14  House Style      2925 non-null   object 
 15  Overall Qual     2925 non-null   int64  
 16  Overall Cond     2925 non-null   int64  
 17  Year Built    

In [15]:
df_nums = df.select_dtypes(exclude = ["object"]) # 排除物件類型
df_objs = df.select_dtypes(include = ["object"]) # 只保留物件類型
df_nums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Lot Frontage     2925 non-null   float64
 1   Lot Area         2925 non-null   int64  
 2   Overall Qual     2925 non-null   int64  
 3   Overall Cond     2925 non-null   int64  
 4   Year Built       2925 non-null   int64  
 5   Year Remod/Add   2925 non-null   int64  
 6   Mas Vnr Area     2925 non-null   float64
 7   BsmtFin SF 1     2925 non-null   float64
 8   BsmtFin SF 2     2925 non-null   float64
 9   Bsmt Unf SF      2925 non-null   float64
 10  Total Bsmt SF    2925 non-null   float64
 11  1st Flr SF       2925 non-null   int64  
 12  2nd Flr SF       2925 non-null   int64  
 13  Low Qual Fin SF  2925 non-null   int64  
 14  Gr Liv Area      2925 non-null   int64  
 15  Bsmt Full Bath   2925 non-null   float64
 16  Bsmt Half Bath   2925 non-null   float64
 17  Full Bath     

In [16]:
df_objs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   MS SubClass     2925 non-null   object
 1   MS Zoning       2925 non-null   object
 2   Street          2925 non-null   object
 3   Lot Shape       2925 non-null   object
 4   Land Contour    2925 non-null   object
 5   Utilities       2925 non-null   object
 6   Lot Config      2925 non-null   object
 7   Land Slope      2925 non-null   object
 8   Neighborhood    2925 non-null   object
 9   Condition 1     2925 non-null   object
 10  Condition 2     2925 non-null   object
 11  Bldg Type       2925 non-null   object
 12  House Style     2925 non-null   object
 13  Roof Style      2925 non-null   object
 14  Roof Matl       2925 non-null   object
 15  Exterior 1st    2925 non-null   object
 16  Exterior 2nd    2925 non-null   object
 17  Mas Vnr Type    1152 non-null   object
 18  Exter Qu

In [17]:
df_objs = pd.get_dummies(df_objs, drop_first = True)
df_objs = df_objs.astype(int)
df_objs

MS SubClass_150  MS SubClass_160  MS SubClass_180  MS SubClass_190  \
0                   0                0                0                0   
1                   0                0                0                0   
2                   0                0                0                0   
3                   0                0                0                0   
4                   0                0                0                0   
...               ...              ...              ...              ...   
2920                0                0                0                0   
2921                0                0                0                0   
2922                0                0                0                0   
2923                0                0                0                0   
2924                0                0                0                0   

      MS SubClass_20  MS SubClass_30  MS SubClass_40  MS SubClass_45  \
0                  1               0               0               0   
1                  1               0               0               0   
2                  1               0               0               0   
3                  1               0               0               0   
4                  0               0               0               0   
...              ...             ...             ...             ...   
2920               0               0               0               0   
2921               1               0               0               0   
2922               0               0               0               0   
2923               1               0               0               0   
2924               0               0               0               0   

      MS SubClass_50  MS SubClass_60  ...  Sale Type_ConLw  Sale Type_New  \
0                  0               0  ...                0              0   
1                  0               0  ...                0              0   
2                  0               0  ...                0              0   
3                  0               0  ...                0              0   
4                  0               1  ...                0              0   
...              ...             ...  ...              ...            ...   
2920               0               0  ...                0              0   
2921               0               0  ...                0              0   
2922               0               0  ...                0              0   
2923               0               0  ...                0              0   
2924               0               1  ...                0              0   

      Sale Type_Oth  Sale Type_VWD  Sale Type_WD   Sale Condition_AdjLand  \
0                 0              0              1                       0   
1                 0              0              1                       0   
2                 0              0              1                       0   
3                 0              0              1                       0   
4                 0              0              1                       0   
...             ...            ...            ...                     ...   
2920              0              0              1                       0   
2921              0              0              1                       0   
2922              0              0              1                       0   
2923              0              0              1                       0   
2924              0              0              1                       0   

      Sale Condition_Alloca  Sale Condition_Family  Sale Condition_Normal  \
0                         0                      0                      1   
1                         0                      0                      1   
2                         0                      0                      1   
3                         0                      0                    

In [18]:
fial_df = df_nums.join(df_objs)
fial_df

Lot Frontage  Lot Area  Overall Qual  Overall Cond  Year Built  \
0       141.000000     31770             6             5        1960   
1        80.000000     11622             5             6        1961   
2        81.000000     14267             6             6        1958   
3        93.000000     11160             7             5        1968   
4        74.000000     13830             5             5        1997   
...            ...       ...           ...           ...         ...   
2920     37.000000      7937             6             6        1984   
2921     75.144444      8885             5             5        1983   
2922     62.000000     10441             5             5        1992   
2923     77.000000     10010             5             5        1974   
2924     74.000000      9627             7             5        1993   

      Year Remod/Add  Mas Vnr Area  BsmtFin SF 1  BsmtFin SF 2  Bsmt Unf SF  \
0               1960         112.0         639.0           0.0        441.0   
1               1961           0.0         468.0         144.0        270.0   
2               1958         108.0         923.0           0.0        406.0   
3               1968           0.0        1065.0           0.0       1045.0   
4               1998           0.0         791.0           0.0        137.0   
...              ...           ...           ...           ...          ...   
2920            1984           0.0         819.0           0.0        184.0   
2921            1983           0.0         301.0         324.0        239.0   
2922            1992           0.0         337.0           0.0        575.0   
2923            1975           0.0        1071.0         123.0        195.0   
2924            1994          94.0         758.0           0.0        238.0   

      ...  Sale Type_ConLw  Sale Type_New  Sale Type_Oth  Sale Type_VWD  \
0     ...                0              0              0              0   
1     ...                0              0              0              0   
2     ...                0              0              0              0   
3     ...                0              0              0              0   
4     ...                0              0              0              0   
...   ...              ...            ...            ...            ...   
2920  ...                0              0              0              0   
2921  ...                0              0              0              0   
2922  ...                0              0              0              0   
2923  ...                0              0              0              0   
2924  ...                0              0              0              0   

      Sale Type_WD   Sale Condition_AdjLand  Sale Condition_Alloca  \
0                 1                       0                      0   
1                 1                       0                      0   
2                 1                       0                      0   
3                 1                       0                      0   
4                 1                       0                      0   
...             ...                     ...                    ...   
2920              1                       0                      0   
2921              1                       0                      0   
2922              1                       0                      0   
2923              1                       0                      0   
2924              1                       0                      0   

      Sale Condition_Family  Sale Condition_Normal  Sale Condition_Partial  
0                         0                      1                       0  
1                         0                      1                       0  
2                         0                      1                       0  
3                         0                      1                       0  
4                         0                      1               

In [19]:
fial_df2 = pd.concat([df_nums, df_objs], axis = 1)
fial_df2

Lot Frontage  Lot Area  Overall Qual  Overall Cond  Year Built  \
0       141.000000     31770             6             5        1960   
1        80.000000     11622             5             6        1961   
2        81.000000     14267             6             6        1958   
3        93.000000     11160             7             5        1968   
4        74.000000     13830             5             5        1997   
...            ...       ...           ...           ...         ...   
2920     37.000000      7937             6             6        1984   
2921     75.144444      8885             5             5        1983   
2922     62.000000     10441             5             5        1992   
2923     77.000000     10010             5             5        1974   
2924     74.000000      9627             7             5        1993   

      Year Remod/Add  Mas Vnr Area  BsmtFin SF 1  BsmtFin SF 2  Bsmt Unf SF  \
0               1960         112.0         639.0           0.0        441.0   
1               1961           0.0         468.0         144.0        270.0   
2               1958         108.0         923.0           0.0        406.0   
3               1968           0.0        1065.0           0.0       1045.0   
4               1998           0.0         791.0           0.0        137.0   
...              ...           ...           ...           ...          ...   
2920            1984           0.0         819.0           0.0        184.0   
2921            1983           0.0         301.0         324.0        239.0   
2922            1992           0.0         337.0           0.0        575.0   
2923            1975           0.0        1071.0         123.0        195.0   
2924            1994          94.0         758.0           0.0        238.0   

      ...  Sale Type_ConLw  Sale Type_New  Sale Type_Oth  Sale Type_VWD  \
0     ...                0              0              0              0   
1     ...                0              0              0              0   
2     ...                0              0              0              0   
3     ...                0              0              0              0   
4     ...                0              0              0              0   
...   ...              ...            ...            ...            ...   
2920  ...                0              0              0              0   
2921  ...                0              0              0              0   
2922  ...                0              0              0              0   
2923  ...                0              0              0              0   
2924  ...                0              0              0              0   

      Sale Type_WD   Sale Condition_AdjLand  Sale Condition_Alloca  \
0                 1                       0                      0   
1                 1                       0                      0   
2                 1                       0                      0   
3                 1                       0                      0   
4                 1                       0                      0   
...             ...                     ...                    ...   
2920              1                       0                      0   
2921              1                       0                      0   
2922              1                       0                      0   
2923              1                       0                      0   
2924              1                       0                      0   

      Sale Condition_Family  Sale Condition_Normal  Sale Condition_Partial  
0                         0                      1                       0  
1                         0                      1                       0  
2                         0                      1                       0  
3                         0                      1                       0  
4                         0                      1               

# 5. 平均絕對誤差 (MAE, Mean Absolute Error)

In [20]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [21]:
california = datasets.fetch_california_housing()
X = california.data
y = california.target
print(X)
print(y)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [23]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [24]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print("MSE:", mse)
print("MAE:", mae)

MSE: 0.555891598695242
MAE: 0.5332001304956994


# 6. 交叉驗證 (Cross Validation with cross_val_score)

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df = pd.read_csv("./Advertising.csv")
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [27]:
from sklearn.model_selection import train_test_split
X = df.drop("sales", axis = 1)
y = df["sales"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# 7. 特徵縮放

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [29]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [30]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model, X_train, y_train, cv = 5, scoring="neg_mean_squared_error")
print(score)
print(abs(score.mean()))

[-4.19295353 -1.50064402 -2.10907967 -2.54135514 -4.37293066]
2.943392602590042
