# 1. max, min, argmax, argmin

In [1]:
import numpy as np

In [2]:
ranIntValue = np.random.randint(0,50,10)
ranIntValue

array([19, 20, 44, 49, 26, 15, 48, 19,  8, 27])

In [3]:
ranIntValue.max()

49

In [4]:
ranIntValue.argmax() #找到最大值的index

3

In [5]:
ranIntValue.min()

8

In [6]:
ranIntValue.argmin() #找到最小值的index

8

# 2. Indexing-and-Selection

In [7]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr[4]

7

In [9]:
arr[1:5]

array([4, 5, 6, 7])

In [10]:
arr[:5]

array([3, 4, 5, 6, 7])

In [11]:
arr[5:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [12]:
arr[-3:] = 99
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 99, 99, 99])

In [13]:
myList = list(range(7,15))
print(myList)
newList = myList[2:5]
print(newList)
newList[1] = 77
print("=======================")
print(myList)
print(newList)

[7, 8, 9, 10, 11, 12, 13, 14]
[9, 10, 11]
[7, 8, 9, 10, 11, 12, 13, 14]
[9, 77, 11]


In [14]:
arr2 = np.arange(1,11)
print(arr2)
newArray = arr2[:7]
print(newArray)
newArray[0] = 999
print("=======================")
print(arr2)
print(newArray)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[999   2   3   4   5   6   7   8   9  10]
[999   2   3   4   5   6   7]


# 3. 索引二維陣列 (矩陣)

In [15]:
arra_2d = np.array(([5,10,15],
                    [20,25,30],
                    [19,18,45],
                    [26,29,32]))

In [16]:
arra_2d[1]

array([20, 25, 30])

In [17]:
arra_2d[1][0]

20

In [18]:
arra_2d[1,0]

20

In [19]:
arra_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [19, 18, 45],
       [26, 29, 32]])

In [20]:
arra_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
arra_2d[2,:]

array([19, 18, 45])

# 4. 條件選擇

In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

# 5. NumPy 運算

In [25]:
arr = np.arange(0,10)
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr * 2)
print(arr ** 2)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


# 6. 陣列的摘要統計

In [26]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr.sum()

55

In [28]:
arr.mean()

5.5

In [29]:
print(arr.var()) #計算陣列arr中元素的方差
print(arr.std()) #計算陣列arr中元素的標準差


8.25
2.8722813232690143


# 7. Import NumPy as np

In [30]:
import numpy as np

# 8. 創建一個包含10個零的陣列

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 9. 創建一個包含10個1的陣列希望是5x2的

In [32]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# 10. 產生10個5的陣列

In [33]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 11. 創建一個包含從10到50的整數的陣列

In [34]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# 12. 要創建一個包含從10到50的所有偶數整數的陣列

In [35]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# 13. 要創建一個3x3矩陣，其中包含從0到8的值

In [36]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 14. 要創建一個3x3的單位矩陣 (identity matrix)

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 15. 要使用NumPy生成一個介於0到1之間的隨機數

In [38]:
np.random.rand(1)

array([0.76524067])

# 16. 要使用NumPy生成一個包含25個從標準正態分布(平均值為0，標準差為1的正態分布)抽樣的隨機數陣列

In [39]:
np.random.randn(25)

array([-0.81584114, -0.49903091,  0.34292035,  2.29426128, -1.22425555,
        0.14209494,  0.46491812, -1.18648264, -1.0177709 , -0.97432762,
        0.35476059,  0.33627906,  0.68667065,  0.06194929,  0.99609225,
        0.57217049,  0.4164257 , -0.50626172,  0.24709172,  0.16836641,
        0.22594236, -1.52210486,  0.83144899, -0.35457208, -1.38478823])

# 17. 使用mat創建矩陣

In [40]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [43]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# 18. Series

In [44]:
import pandas as pd

In [45]:
myIndx = ["USA","Canada","Mexico"]
myData = [1776,1867,1821]
myser = pd.Series(data = myData)
print(myser)

0    1776
1    1867
2    1821
dtype: int64


In [46]:
myuser = pd.Series(data = myData, index = myIndx)
myuser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [47]:
import numpy as np
ran_data = np.random.randint(0,100,4)
ran_data

array([94, 67, 97, 57])

In [48]:
names = ["Ken","Vivin","Lucy","Joy"]
ages = pd.Series(ran_data, names)
ages

Ken      94
Vivin    67
Lucy     97
Joy      57
dtype: int32

In [49]:
ags = {"Gigi":5,"Any":10,"Carlos":15}
afeSer = pd.Series(ags)
afeSer

Gigi       5
Any       10
Carlos    15
dtype: int64

In [50]:
q1 = {"Japan":80,"China":450,"India":200,"USA":250}
q2 = {"Brazil":100,"China":500,"India":210,"USA":260}
sales_Q1 = pd.Series(q1)
sales_Q2 = pd.Series(q2)
print(sales_Q1["Japan"])
print(sales_Q1[0])
print(sales_Q2["Brazil"])

80
80
100


C:\Users\hankc\AppData\Local\Temp\ipykernel_4996\2889049979.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sales_Q1[0])


In [51]:
sales_Q2.keys()

Index(['Brazil', 'China', 'India', 'USA'], dtype='object')

In [52]:
sales_Q2 * 2

Brazil     200
China     1000
India      420
USA        520
dtype: int64

In [53]:
sales_Q1 + sales_Q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [54]:
sales_Q1.add(sales_Q2, fill_value=0) #fill_value=0表示缺失值用0

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

# 19. DataFrames

In [55]:
import pandas as pd
import numpy as np
np.random.seed(101)
myData = np.random.randint(0,101,(4,3))
print(myData)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [56]:
myindex = ['CA','NY','AZ','TX']
Mycolumns = ['Jan','Feb','Mar']

In [57]:
df = pd.DataFrame(data = myData)
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [58]:
df = pd.DataFrame(data = myData, index = myindex)
df

0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63

In [59]:
df = pd.DataFrame(data = myData, index = myindex, columns = Mycolumns)
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63